###
GET http://localhost:3000/users


###
GET http://localhost:3000/users/650479cc549ada7b357f66c3


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "teste",
    "email": "teste@gmail.com",
    "biography": "teste bio",
    "birthdayDate": "1111-11-11T11:11:11.111Z",
    "password": "teste1234"
}

###
PUT http://localhost:3000/users/650479cc549ada7b357f66c3
Content-Type: application/json

{
    "name": "testeEdit",
    "email": "teste@gmail.com",
    "biography": "teste bio",
    "birthdayDate": "1111-11-11T11:11:11.111Z"
}

###
DELETE http://localhost:3000/users/650479cc549ada7b357f66c3

//-------------------posts api----------------------------

###
GET http://localhost:3000/posts


###
GET http://localhost:3000/posts/65047dcd74a4a5e71f680ba0


###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTA0NzljYzU0OWFkYTdiMzU3ZjY2YzMiLCJ1c2VybmFtZSI6InRlc3RlRWRpdCIsImlhdCI6MTY5NDc5NzQ4OCwiZXhwIjoxNjk0Nzk3NTQ4fQ.y1W37QITfRLRgijkEO0v3oQZRGDDMdit1hoye-569S4

{
    "content": "content post",
    "userId": "650479cc549ada7b357f66c3"
}

###
PUT http://localhost:3000/posts/65048ed323b1ce1182e49290
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTA0NzljYzU0OWFkYTdiMzU3ZjY2YzMiLCJ1c2VybmFtZSI6InRlc3RlRWRpdCIsImlhdCI6MTY5NDc5NzQ4OCwiZXhwIjoxNjk0Nzk3NTQ4fQ.y1W37QITfRLRgijkEO0v3oQZRGDDMdit1hoye-569S4

{
    "content": "content EDIT post"
}

###
DELETE http://localhost:3000/posts/65047dcd74a4a5e71f680ba0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTA0NzljYzU0OWFkYTdiMzU3ZjY2YzMiLCJ1c2VybmFtZSI6InRlc3RlRWRpdCIsImlhdCI6MTY5NDc5NzU2MiwiZXhwIjoxNjk0Nzk3NjIyfQ.xhcOkceo8GmyAdo0w7wkNSy9dsB2GCInExbOQWOC5Nw

//-------------------------------login---------------------

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "teste", 
    "password": "teste1234",
    "access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
}